In [214]:
import pandas as pd
import numpy as np
import os
import glob
from pathlib import Path
import numpy as np

## Dataset 1

In [215]:
meta_data_path = "/home/muhammad/Desktop/Datasets/dataset_anxiety/1_fusion_corpus_anxiety/meta_anxiety.xlsx"

In [216]:
meta_df_fusion = pd.read_excel(meta_data_path)

In [217]:
unique_bai_values_fusion = meta_df_fusion["BAITotal"].unique()

In [218]:
unique_bai_values_fusion

array([ 4.,  9.,  0., 20.,  2., 10., 14., 17., 11.,  1.,  8., 19.,  6.,
        5.,  3., 26., 18.,  7., 37., 16., 43., 24., 12., 15., 13., 27.,
       51., 21., 31., 28., 23., 47., 40., 33., nan, 39., 32., 25., 44.,
       30., 29., 34., 35., 22., 36., 38., 60., 49., 41.])

In [219]:
meta_df_fusion["BAITotal"].nunique()

48

In [220]:
bai_score_fusion = meta_df_fusion["BAITotal"].values

In [221]:

# variable to hold the count

In [222]:
distinct_value_count_fusion = {}

for single_score in bai_score_fusion:
    
    if distinct_value_count_fusion.get(single_score):
        
        distinct_value_count_fusion[single_score] = distinct_value_count_fusion[single_score] + 1
        
    else:
        
        distinct_value_count_fusion[single_score] = 1
    

In [223]:
distinct_value_count_fusion

{4.0: 802,
 9.0: 557,
 0.0: 1021,
 20.0: 184,
 2.0: 545,
 10.0: 342,
 14.0: 263,
 17.0: 112,
 11.0: 310,
 1.0: 545,
 8.0: 490,
 19.0: 111,
 6.0: 537,
 5.0: 484,
 3.0: 465,
 26.0: 134,
 18.0: 139,
 7.0: 586,
 37.0: 23,
 16.0: 366,
 43.0: 12,
 24.0: 100,
 12.0: 434,
 15.0: 193,
 13.0: 187,
 27.0: 25,
 51.0: 7,
 21.0: 160,
 31.0: 56,
 28.0: 43,
 23.0: 72,
 47.0: 15,
 40.0: 51,
 33.0: 83,
 nan: 1,
 nan: 1,
 nan: 1,
 nan: 1,
 nan: 1,
 nan: 1,
 nan: 1,
 nan: 1,
 nan: 1,
 39.0: 27,
 32.0: 44,
 25.0: 65,
 44.0: 25,
 30.0: 18,
 29.0: 31,
 34.0: 44,
 35.0: 20,
 22.0: 101,
 36.0: 14,
 38.0: 78,
 60.0: 8,
 49.0: 8,
 41.0: 19,
 nan: 1,
 nan: 1}

## Dataset 2

In [255]:
meta_data_anxiety_bai ="/home/muhammad/Desktop/Datasets/dataset_anxiety/1_Metadata_Anxiety_BAI_Checked/Metadaten_Anxiety_BAI_checked1.xlsx"

In [256]:
meta_data = pd.read_excel(meta_data_anxiety_bai)

In [257]:
unique_bai_values = meta_data["BAITotal"].unique()

In [258]:
unique_bai_values

array([ 4.,  9.,  0., 20.,  2., 10., 14., 17., 11.,  1.,  8., 19.,  6.,
        5.,  3., 26., 18.,  7., 37., 16., 43., 24., 12., 15., 13., 27.,
       51., 21., 31., 28., 23., 47., 40., 33., nan, 39., 32., 25., 44.,
       30., 29., 34., 35., 22., 36., 38., 60., 49., 41.])

In [259]:
meta_data["BAITotal"].nunique()

48

In [260]:
bai_total = meta_data["BAITotal"].values

In [261]:
bai_total

array([ 4.,  4.,  4., ..., 11., 11., 11.])

In [262]:
distinct_value_count = {}

for single_score in bai_total:
    
    if distinct_value_count.get(single_score):
        
        distinct_value_count[single_score] = distinct_value_count[single_score] + 1
        
    else:
        
        distinct_value_count[single_score] = 1

In [263]:
distinct_value_count

{4.0: 882,
 9.0: 604,
 0.0: 1098,
 20.0: 207,
 2.0: 595,
 10.0: 378,
 14.0: 287,
 17.0: 129,
 11.0: 336,
 1.0: 572,
 8.0: 529,
 19.0: 121,
 6.0: 587,
 5.0: 518,
 3.0: 505,
 26.0: 148,
 18.0: 158,
 7.0: 638,
 37.0: 28,
 16.0: 378,
 43.0: 16,
 24.0: 109,
 12.0: 464,
 15.0: 211,
 13.0: 207,
 27.0: 32,
 51.0: 8,
 21.0: 164,
 31.0: 60,
 28.0: 45,
 23.0: 83,
 47.0: 16,
 40.0: 53,
 33.0: 89,
 nan: 1,
 nan: 1,
 nan: 1,
 nan: 1,
 nan: 1,
 nan: 1,
 nan: 1,
 nan: 1,
 nan: 1,
 39.0: 28,
 32.0: 47,
 25.0: 70,
 44.0: 25,
 30.0: 20,
 29.0: 32,
 34.0: 47,
 35.0: 20,
 22.0: 104,
 36.0: 15,
 38.0: 78,
 60.0: 8,
 49.0: 8,
 41.0: 21,
 nan: 1,
 nan: 1}

### Distinct files in two datasets

In [269]:
file_names = meta_data["Filename"].values

In [282]:
file_names

array(['vp_01_00_ID_AA1711', 'vp_01_01_tat_cry_aa1711',
       'vp_01_02_tat_cookie_aa1711', ..., 'vp_078_01_00_sg_cream.wav',
       'vp_078_01_00_sg_good_evening.wav',
       'vp_078_01_00_story_disgust_childhood.wav'], dtype=object)

In [283]:
file_names.size

10789

In [284]:
file_names_fusion = meta_df_fusion["Filename_global"].values

In [285]:
"402_counting" in file_names_fusion

True

In [272]:
file_names_fusion.size

9967

In [273]:
file_names_fusion_set = set(file_names_fusion)
file_names_set=set(file_names)

In [274]:
result_differrence = list(set(file_names_fusion_set).symmetric_difference(set(file_names_set)))

In [275]:
len(result_differrence)

20747

In [276]:
file_names_fusion_set.intersection(file_names_set)

set()